package com.cncmes.base;

public enum TaskItems {
	MODEL,STATE,ROBOTIP,MATERIALIDS,RACKIDS,SLOTIDS,MACHINESTATE,SCHEDULERTASKID,LINENAME,
	MACHINEIP,ERRORCODE,ROBOTSTATE,MATERIALSTATES,ENGINEER,ALARMTIME;
}
