package com.cncmes.base;

public enum SchedulerDataItems {
	IP,PORT,MODEL,STATE,LINENAME,RACKID,SLOTNO,WORKPIECEID,TASKID,CONTROLCENTER,
	PROCESSNAME,PROCESSQTY,PROGRAM,NCMODEL,SIMTIME,SURFACE,BATTERY,
	POSITION,MACHINETIME,PROGRESS,WKZONEQTY,CAPACITY,QTYTOTAL,
	QTYCONNECTING,QTYWORKING,QTYSTANDBY,QTYSHUTDOWN,QTYALARM,QTYPLAN,QTYFINISH,
	QTYWORKPIECE,QTYDRILLING,QTYMILLING,QTYTAPPING,TIMEDRILLING,TIMEMILLING,TIMETAPPING,
	SLOT1,SLOT2,SLOT3,SLOT4,SLOT5,SLOT6,SLOT7,SLOT8,SLOT9,SLOT10,SLOT11,SLOT12,SLOT13,SLOT14,GRIPMATERIAL,WPIDS,WPSTATES,WPSLOTIDS;
}
