package com.cncmes.base;

/**
 * Robot Running Data Items
 * @author LI ZI LONG
 *
 */
public enum RobotItems {
	IP,PORT,MODEL,STATE,LINENAME,SCANNERIP,POSITION,CAPACITY,GRIPMATERIAL,
	SLOT1,SLOT2,SLOT3,SLOT4,SLOT5,SLOT6,SLOT7,SLOT8,SLOT9,SLOT10,SLOT11,SLOT12,SLOT13,
	SLOT14,SLOT15,LOADQTY,TASKID,WPIDS,WPSTATES,WPSLOTIDS,CMD,TAGNAME,BATTERY,POS_TAR,
	POS_PARKING,POS_CHARGING,OP_MOVETORACK,OP_MOVETOMACHINE,SLEEP,OP_PNPTESTING,OP_STOPPNPTESTING,OP_GOTOCHARGE;
}
