package com.cncmes.base;

public enum CncItems {
	IP,PORT,MODEL,FTPIP,STATE,EXPMACHINETIME,TOOLNO,FEEDRATE,RPM,COMMAND,STARTTIME,LINENAME,
	WKZONEQTY,WKPIECE1,WKPIECE2,WKPIECE3,WKPIECE4,WKPIECE5,WKPIECE6,WKPIECE7,WKPIECE8,WKPIECE9,WKPIECE10,WKPIECE11,WKPIECE12,WKPIECE13,WKPIECE14;
}
