package com.cncmes.base;

/**
 * Scheduler Running Data Items
 * @author LI ZI LONG
 *
 */
public enum SchedulerDataItems {
	IP,PORT,MODEL,STATE,LINENAME,RACKID,SLOTNO,WORKPIECEID,
	PROCESSNAME,PROCESSQTY,PROGRAM,NCMODEL,SIMTIME,SURFACE,BATTERY,
	POSITION,MACHINETIME,PROGRESS,WKZONEQTY,CAPACITY,QTYTOTAL,
	QTYCONNECTING,QTYWORKING,QTYSTANDBY,QTYSHUTDOWN,QTYALARM,QTYPLAN,QTYFINISH;
}
