package com.cncmes.base;

public enum RobotItems {
	IP,PORT,MODEL,STATE,LINENAME,SCANNERIP,POSITION,CAPACITY,SLOT1,SLOT2,SLOT3,SLOT4,
	SLOT5,SLOT6,SLOT7,SLOT8,SLOT9,SLOT10,SLOT11,SLOT12,SLOT13,SLOT14,SLOT15;
}
