package com.cncmes.base;

public enum TaskItems {
	MODEL,STATE,ROBOTIP,MATERIALIDS,RACKIDS,SLOTIDS,MACHINESTATE,SCHEDULERTASKID,LINENAME,
	MACHINEIP,ERRORCODE,ROBOTSTATE,MATERIALSTATES,ENGINEER,ALARMTIME,
	MACHINEWPIDS,MACHINEWPSLOTIDS,MACHINEWPSTATES,STARTHANDLINGTIME,HANDLINGIP,
	ROBOTWPIDS,ROBOTWPSLOTIDS,ROBOTWPSTATES,SUBPROGRAMS,MAINPROGRAM,MACHINEKEY,ROBOTKEY;
}
