package com.cncmes.base;

public enum RobotItems {
	IP,PORT,MODEL,STATE,LINENAME,SCANNERIP,POSITION,CAPACITY,GRIPMATERIAL,
	SLOT1,SLOT2,SLOT3,SLOT4,SLOT5,SLOT6,SLOT7,SLOT8,SLOT9,LOADQTY,TASKID,
	WPIDS,WPSTATES,WPSLOTIDS,CMD,TAGNAME,BATTERY,POS_TAR,POS_PARKING,POS_CHARGING;
}
