package com.cncmes.base;

public enum WorkpieceItems {
	ID,STATE,SPECID,LINENAME,CONVEYORID,CONVEYORSLOTNO,
	PROCQTY,CURPROC,PROC1STATUS,PROC2STATUS,PROC3STATUS,PROC4STATUS,PROC5STATUS,PROC6STATUS;
}
