package com.cncmes.base;

/**
 * CNC Running Data Items
 * @author LI ZI LONG
 *
 */
public enum CncItems {
	IP,PORT,MODEL,FTPIP,STATE,CTRL,EXPMACHINETIME,PARAS,ALARMMSG,COMMAND,LINENAME,FINISHSHOW,PROGRESS,
	WKZONEQTY,D_WPID_ZN1,D_WPID_ZN2,D_WPID_ZN3,D_WPID_ZN4,D_WPID_ZN5,D_WPID_ZN6,D_WPID_ZN7,D_WPID_ZN8,
	D_WPID_ZN9,D_WPID_ZN10,D_WPID_ZN11,D_WPID_ZN12,D_WPID_ZN13,D_WPID_ZN14,D_TASKID,LASTSTATE,
	WPIDS,WPSTATES,WPZONES,DT_DATE,DT_ALARM,D_ROBOTL,D_ROBOTUL,D_ROBOTPOSL,D_ROBOTPOSUL,
	DT_READYLOADING,DT_FINISHUNLOADING,DT_MACHINING_START,DT_MACHINING_FINISH,DT_START_ZN1,
	DT_START_ZN2,DT_START_ZN3,DT_START_ZN4,DT_START_ZN5,DT_START_ZN6,DT_START_ZN7,DT_START_ZN8,
	DT_START_ZN9,DT_START_ZN10,DT_START_ZN11,DT_START_ZN12,DT_START_ZN13,DT_START_ZN14,D_NCPROG_ZN1,
	D_NCPROG_ZN2,D_NCPROG_ZN3,D_NCPROG_ZN4,D_NCPROG_ZN5,D_NCPROG_ZN6,D_NCPROG_ZN7,D_NCPROG_ZN8,
	D_NCPROG_ZN9,D_NCPROG_ZN10,D_NCPROG_ZN11,D_NCPROG_ZN12,D_NCPROG_ZN13,D_NCPROG_ZN14,
	D_SPECNO_ZN1,D_SPECNO_ZN2,D_SPECNO_ZN3,D_SPECNO_ZN4,D_SPECNO_ZN5,D_SPECNO_ZN6,D_SPECNO_ZN7,
	D_SPECNO_ZN8,D_SPECNO_ZN9,D_SPECNO_ZN10,D_SPECNO_ZN11,D_SPECNO_ZN12,D_SPECNO_ZN13,D_SPECNO_ZN14,
	D_ERR,DT_MACHINING_ZNS,DT_FINISH_ZNS_QTY,DT_SIMT_ZN1,DT_SIMT_ZN2,DT_SIMT_ZN3,DT_SIMT_ZN4,DT_SIMT_ZN5,
	DT_SIMT_ZN6,DT_SIMT_ZN7,DT_SIMT_ZN8,DT_SIMT_ZN9,DT_SIMT_ZN10,DT_SIMT_ZN11,DT_SIMT_ZN12,DT_SIMT_ZN13,
	DT_SIMT_ZN14,DT_CLEANING_START1,DT_CLEANING_STOP1,DT_CLEANING_START2,DT_CLEANING_STOP2,
	HELPER_IP,HELPER_PORT,TAGNAME,SUBPROGRAMS,MAINPROGRAM,OP_OPENDOOR,OP_CLOSEDOOR,OP_RELEASEFIXTURE,
	OP_CLAMPFIXTURE,OP_CLEANING,OP_HF_OPENDOOR,OP_HF_CLOSEDOOR,OP_HF_RELEASEFIXTURE,OP_HF_CLAMPFIXTURE,
	OP_HF_HOMEDOOR,OP_HF_RESETDOOR,OP_AXIS4MOVE,RECORD_FIXTURE_IN_RACK_SLOTID;
}
