package com.cncmes.base;

/**
 * CNC Web API Configuration Items
 * @author LI ZI LONG
 *
 */
public enum CncWebAPIItems {
	ID,BRAND,MODEL,NAME,URL,INPARAS,INPARASTYPE,INPARASVAL,OUTPARAS,OUTPARASTYPE,
	OUTPARASVAL,FTPPORT,FTPUSER,FTPPWD,DEBUGPORT,NCPROGSUB1,NCPROGSUB2,NCPROGSUB3,
	NCPROGSUB4,NCPROGSUB5,NCPROGSUB6,NCPROGSUB7,NCPROGSUB8,NCPROGSUB9,NCPROGSUB10,
	NCPROGSUB11,NCPROGSUB12,NCPROGSUB13,NCPROGSUB14,NCPROGMAIN,DEBUGIP,OPERATOR,
	SENSORCHECK,COORDINATE1,COORDINATE2,COORDINATE3,COORDINATE4,COORDINATE5,COORDINATE6,
	COORDINATE7,COORDINATE8,COORDINATE9,COORDINATE10,COORDINATE11,COORDINATE12,
	COORDINATE13,COORDINATE14;
}
