package com.cncmes.base;

public enum DeviceOP {
	CNC_OPENDOOR,CNC_CLOSEDOOR,CNC_RELEASEFIXTURE,CNC_CLAMPFIXTURE,CNC_CLEANING,
	CNC_HF_OPENDOOR,CNC_HF_CLOSEDOOR,CNC_HF_RELEASEFIXTURE,CNC_HF_CLAMPFIXTURE,
	CNC_AXIS4_MOVE,ROBOT_MOVETORACK,ROBOT_MOVETOMACHINE,ROBOT_PNPTESTING,ROBOT_GOTOCHARGE;
}
