package com.cncmes.base;

/**
 * Task Info Items
 * @author LI ZI LONG
 *
 */
public enum TaskItems {
	MODEL,STATE,ROBOTIP,MATERIALIDS,RACKIDS,SLOTIDS,MACHINESTATE,SCHEDULERTASKID,LINENAME,
	MACHINEIP,ERRORCODE,ROBOTSTATE,MATERIALSTATES,ENGINEER,ALARMTIME;
}
