package com.cncmes.base;

/**
 * Workpieces Running Data Items
 * @author LI ZI LONG
 *
 */
public enum WorkpieceItems {
	ID,STATE,SPECID,LINENAME,CONVEYORID,CONVEYORSLOTNO,PROCQTY,PROCESS,NCMODEL,PROGRAM,SURFACE,MACHINETIME,
	CURPROC,PROC1STATUS,PROC2STATUS,PROC3STATUS,PROC4STATUS,PROC5STATUS,PROC6STATUS;
}
